#ifndef MEDICINE_CAR_TEST_CONFIG_H
#define MEDICINE_CAR_TEST_CONFIG_H

#include "medicine_car_config.h"

/* Select the firmware test run from main(). */
#define MED_CAR_TEST_MODE_NONE             0U
#define MED_CAR_TEST_MODE_MOTOR            1U
#define MED_CAR_TEST_MODE_GRAY             2U
#define MED_CAR_TEST_MODE_LED_BEEP         3U
#define MED_CAR_TEST_MODE_ROUTE1           4U
#define MED_CAR_TEST_MODE_ROUTE2           5U
#define MED_CAR_TEST_MODE_ENCODER          6U
#define MED_CAR_TEST_MODE_GRAY_TRACE       7U
#define MED_CAR_TEST_MODE_WHEEL_MATCH      8U
#define MED_CAR_TEST_MODE_VISION_UART      9U
#define MED_CAR_TEST_MODE_DRUG_SENSOR     10U
#define MED_CAR_TEST_MODE_SENSOR_DOOR     12U
#define MED_CAR_TEST_MODE_CROSS_TURN      13U
#define MED_CAR_TEST_MODE_DISTANCE_CALIB  MED_CAR_TEST_MODE_CROSS_TURN
#define MED_CAR_TEST_MODE_ROUTE3_8        14U
#define MED_CAR_TEST_MODE_WIGGLE_CALIB    15U
#define MED_CAR_TEST_MODE_RP2             16U
#define MED_CAR_TEST_MODE                 MED_CAR_TEST_MODE_RP2

/* Motor, gray sensor, LED and encoder tests. */
#define MED_CAR_TEST_MOTOR_PWM              2000
#define MED_CAR_TEST_MOTOR_RUN_MS           100U
#define MED_CAR_TEST_MOTOR_STOP_MS          800U
#define MED_CAR_TEST_GRAY_PRINT_MS          500U
#define MED_CAR_TEST_GRAY_TRACE_PWM         MED_CAR_TRACE_PWM
#define MED_CAR_TEST_GRAY_TRACE_DISTANCE   3000U
#define MED_CAR_TEST_GRAY_TRACE_PAUSE_MS   1000U
#define MED_CAR_TEST_LED_BEEP_STEP_MS       500U
#define MED_CAR_TEST_ENCODER_PWM            2000
#define MED_CAR_TEST_ENCODER_RUN_MS        2000U
#define MED_CAR_TEST_ENCODER_SAMPLE_MS      200U

/* Wheel matching, UART and drug sensor tests. */
#define MED_CAR_TEST_WHEEL_MATCH_LEFT_PWM   1860
#define MED_CAR_TEST_WHEEL_MATCH_RIGHT_PWM  2000
#define MED_CAR_TEST_WHEEL_MATCH_RUN_MS     3000U
#define MED_CAR_TEST_WHEEL_MATCH_SAMPLE_MS   200U
#define MED_CAR_TEST_WHEEL_MATCH_PAUSE_MS   1000U
#define MED_CAR_TEST_VISION_PRINT_MS        1000U
#define MED_CAR_TEST_DRUG_PRINT_MS           500U
#define MED_CAR_VISION_UART_TIMEOUT_MS      3000U

/* Door, route 3-8 and cross-turn tests. */
#define MED_CAR_TEST_SENSOR_DOOR_PWM         4000
#define MED_CAR_TEST_SENSOR_DOOR_DISTANCE   6000U
#define MED_CAR_TEST_SENSOR_DOOR_PAUSE_MS   3000U
#define MED_CAR_TEST_R3_8_VISION_INTERVAL_MS 500U
#define MED_CAR_TEST_R3_8_DRUG_POLL_MS        100U
#define MED_CAR_TEST_R3_8_IDLE_PRINT_MS      2000U
#define MED_CAR_TEST_CROSS_TURN_PWM          MED_CAR_TRACE_PWM
#define MED_CAR_TEST_CROSS_TURN_CYCLES          3U
#define MED_CAR_TEST_CROSS_TURN_MAX_TICKS   3000U
#define MED_CAR_TEST_CROSS_TURN_PAUSE_MS    2000U
#define MED_CAR_TEST_CROSS_TURN_DOOR_DISTANCE 6000U
#define MED_CAR_TEST_CROSS_TURN_DOOR_PWM    MED_CAR_TRACE_PWM
#define MED_CAR_TEST_CROSS_TURN_RETURN_DISTANCE 15000U
#define MED_CAR_TEST_CROSS_TURN_LEFT_DOOR_DISTANCE 6000U

/* RP2 wiggle calibration test. */
#define MED_CAR_TEST_WIGGLE_PAUSE_MS        2000U

#endif
