#ifndef MEDICINE_CAR_CONFIG_H
#define MEDICINE_CAR_CONFIG_H

#include <stdint.h>

/*
 * Hardware that has not been built yet stays disabled by default. Enable one
 * flag at a time after the matching pins/peripheral are configured in CubeMX.
 * Encoders are enabled because TIM1/TIM8 and PA8/PA9/PC6/PC7 are configured.
 */
#define MED_CAR_ENABLE_ENCODER          1U
#define MED_CAR_ENABLE_BLUETOOTH        0U
#define MED_CAR_ENABLE_RECOGNITION_UART 0U
#define MED_CAR_ENABLE_TFT              0U
#define MED_CAR_ENABLE_KEYS             0U
#define MED_CAR_ENABLE_DRUG_SENSOR      0U

#define MED_CAR_TEST_MODE_NONE          0U
#define MED_CAR_TEST_MODE_MOTOR         1U
#define MED_CAR_TEST_MODE_GRAY          2U
#define MED_CAR_TEST_MODE_LED_BEEP      3U
#define MED_CAR_TEST_MODE_ROUTE1        4U
#define MED_CAR_TEST_MODE_ROUTE2        5U
#define MED_CAR_TEST_MODE_ENCODER       6U
#define MED_CAR_TEST_MODE_GRAY_TRACE    7U
#define MED_CAR_TEST_MODE_WHEEL_MATCH   8U
#define MED_CAR_TEST_MODE               MED_CAR_TEST_MODE_GRAY_TRACE
#define MED_CAR_TEST_MOTOR_PWM          2000
#define MED_CAR_TEST_MOTOR_RUN_MS       1200U
#define MED_CAR_TEST_MOTOR_STOP_MS      800U
#define MED_CAR_TEST_GRAY_PRINT_MS      500U
#define MED_CAR_TEST_GRAY_TRACE_PWM     1800
#define MED_CAR_TEST_GRAY_TRACE_DISTANCE 3000U
#define MED_CAR_TEST_GRAY_TRACE_PAUSE_MS 1000U
#define MED_CAR_TEST_LED_BEEP_STEP_MS   500U
#define MED_CAR_TEST_ENCODER_PWM        2000
#define MED_CAR_TEST_ENCODER_RUN_MS     2000U
#define MED_CAR_TEST_ENCODER_SAMPLE_MS  200U
#define MED_CAR_TEST_WHEEL_MATCH_LEFT_PWM  1938
#define MED_CAR_TEST_WHEEL_MATCH_RIGHT_PWM 2000
#define MED_CAR_TEST_WHEEL_MATCH_RUN_MS    3000U
#define MED_CAR_TEST_WHEEL_MATCH_SAMPLE_MS 200U
#define MED_CAR_TEST_WHEEL_MATCH_PAUSE_MS  1000U

#define MED_CAR_LEFT_MOTOR_INVERT       1U
#define MED_CAR_RIGHT_MOTOR_INVERT      0U
#define MED_CAR_LEFT_ENCODER_INVERT     0U
#define MED_CAR_RIGHT_ENCODER_INVERT    0U

#define MED_CAR_LEFT_PWM_TRIM_NUM       1938
#define MED_CAR_RIGHT_PWM_TRIM_NUM      2000
#define MED_CAR_PWM_TRIM_DEN            2000

#define MED_CAR_DEFAULT_MISSING_SENSOR  0U
#define MED_CAR_DEFAULT_DRUG_PRESENT    1U
#define MED_CAR_GRAY_BLACK_LEVEL        1U
#define MED_CAR_GRAY_SERIAL_FRAME_SYNC_MS 1U
#define MED_CAR_GRAY_SERIAL_CLK_HIGH_CYCLES 3000U

#define MED_CAR_CODE_PWM_MAX            8000
#define MED_CAR_H7_PWM_PERIOD           1999U

#define MED_CAR_STOP_TICK_MS            20U
#define MED_CAR_STEP_IDLE_DELAY_MS      10U
#define MED_CAR_DELIVERY_WAIT_TIMEOUT_MS 30000U

#define MED_CAR_TURN_LEFT_MS            380U
#define MED_CAR_TURN_RIGHT_MS           380U
#define MED_CAR_TURN_AROUND_MS          760U

#define MED_CAR_LINE_PWM_ADJUST_1       1000
#define MED_CAR_LINE_PWM_ADJUST_2       2000
#define MED_CAR_LINE_PWM_ADJUST_3       3000

#define MED_CAR_DISTANCE_MID            6000U
#define MED_CAR_DISTANCE_FIRST_CHECK    11800U
#define MED_CAR_DISTANCE_SECOND_CHECK   19500U
#define MED_CAR_DISTANCE_THIRD_CHECK    33000U
#define MED_CAR_DISTANCE_RETURN_MID     13000U
#define MED_CAR_DISTANCE_RETURN_CROSS4  5900U
#define MED_CAR_DISTANCE_RETURN_CROSS3  8000U
#define MED_CAR_DISTANCE_HOME_WHITE     9000U

typedef enum {
    MED_CAR_SENSOR_IO1 = 1,
    MED_CAR_SENSOR_IO2 = 2,
    MED_CAR_SENSOR_IO3 = 3,
    MED_CAR_SENSOR_IO4 = 4,
    MED_CAR_SENSOR_IO5 = 5,
    MED_CAR_SENSOR_IO6 = 6,
    MED_CAR_SENSOR_IO7 = 7,
    MED_CAR_SENSOR_IO8 = 8
} MedicineCarSensorId;

#endif
