#ifndef MEDICINE_CAR_CONFIG_H
#define MEDICINE_CAR_CONFIG_H

#include <stdint.h>

/*
 * Hardware that has not been built yet stays disabled by default. Enable one
 * flag at a time after the matching pins/peripheral are configured in CubeMX.
 * Encoders are enabled because TIM1/TIM8 and PA8/PA9/PC6/PC7 are configured.
 */
#define MED_CAR_ENABLE_ENCODER          1U
#define MED_CAR_ENABLE_BLUETOOTH        0U
#define MED_CAR_ENABLE_RECOGNITION_UART 1U
#define MED_CAR_ENABLE_TFT              0U
#define MED_CAR_ENABLE_KEYS             0U
#define MED_CAR_ENABLE_DRUG_SENSOR      1U

#define MED_CAR_VISION_FRAME_BEEP_MS          100U
#define MED_CAR_VISION_BEEP_GAP_MS            100U
#define MED_CAR_MATCH_BEEP_MS                 100U
#define MED_CAR_FORK_STOP_SETTLE_MS         300U

#define MED_CAR_LEFT_MOTOR_INVERT       1U
#define MED_CAR_RIGHT_MOTOR_INVERT      0U
#define MED_CAR_LEFT_ENCODER_INVERT     0U
#define MED_CAR_RIGHT_ENCODER_INVERT    0U

#define MED_CAR_LEFT_PWM_TRIM_NUM       1900
#define MED_CAR_RIGHT_PWM_TRIM_NUM      2000
#define MED_CAR_PWM_TRIM_DEN            2000

#define MED_CAR_DEFAULT_MISSING_SENSOR  1U
#define MED_CAR_DEFAULT_DRUG_PRESENT    1U
#define MED_CAR_DRUG_PRESENT_LEVEL      0U
#define MED_CAR_GRAY_BLACK_LEVEL        0U
#define MED_CAR_GRAY_WHITE_LEVEL        1U
#define MED_CAR_GRAY_SERIAL_FRAME_SYNC_MS 1U
#define MED_CAR_GRAY_SERIAL_CLK_HIGH_CYCLES 3000U

#define MED_CAR_CODE_PWM_MAX            8000
#define MED_CAR_H7_PWM_PERIOD           1999U

#define MED_CAR_STOP_TICK_MS            20U
#define MED_CAR_STEP_IDLE_DELAY_MS      10U
#define MED_CAR_DELIVERY_WAIT_TIMEOUT_MS 30000U

#define MED_CAR_TURN_LEFT_MS            380U
#define MED_CAR_TURN_RIGHT_MS           380U
#define MED_CAR_TURN_AROUND_MS          760U

#define MED_CAR_LINE_PWM_ADJUST_1       100
#define MED_CAR_LINE_PWM_ADJUST_2       200
#define MED_CAR_LINE_PWM_ADJUST_3       400
#define MED_CAR_TRACE_PWM               1700

#define MED_CAR_DISTANCE_MID            6000U
#define MED_CAR_DISTANCE_FIRST_CHECK    11800U
#define MED_CAR_DISTANCE_SECOND_CHECK   19500U
#define MED_CAR_DISTANCE_R3_8_SHORT     800U

#define MED_CAR_TURN_LEFT_LEFT_PWM     -100
#define MED_CAR_TURN_LEFT_RIGHT_PWM     1000
#define MED_CAR_TURN_RIGHT_LEFT_PWM     1200
#define MED_CAR_TURN_RIGHT_RIGHT_PWM   -100
#define MED_CAR_SENSOR_TURN_LEFT_MIN_TICKS   600U
#define MED_CAR_SENSOR_TURN_RIGHT_MIN_TICKS  500U
#define MED_CAR_SENSOR_DIAOTOU_MIN_TICKS     2200U
#define MED_CAR_SENSOR_TURN_CONFIRM_CNT        2U
#define MED_CAR_TURN_MIN_MS             120U
#define MED_CAR_TURN_TIMEOUT_MS         2500U
#define MED_CAR_TURN_POLL_MS            10U

#define MED_CAR_DIAOTOU_LEFT_PWM       -1200
#define MED_CAR_DIAOTOU_RIGHT_PWM       1200
#define MED_CAR_DIAOTOU_MIN_MS          400U
#define MED_CAR_DIAOTOU_TIMEOUT_MS      3500U

#define MED_CAR_DOOR_BLACK_MIN          4U
#define MED_CAR_DOOR_CONFIRM_CNT        2U
#define MED_CAR_DOOR_GUARD_MAX          800U
#define MED_CAR_DOOR_MISS_MAX           5U

#define MED_CAR_CROSS_ADVANCE_MS         200U
#define MED_CAR_CROSS_ADVANCE_PWM       MED_CAR_TRACE_PWM

#define MED_CAR_RETURN_STACK_SIZE         10U
#define MED_CAR_RETURN_PWM                MED_CAR_TRACE_PWM
#define MED_CAR_RETURN_HOME_DISTANCE       6000U
#define MED_CAR_RETURN_CROSS_RETRY_MAX        5U
#define MED_CAR_RETURN_ESCAPE_MS            100U
#define MED_CAR_RETURN_FORK_CLEAR_MS        100U
#define MED_CAR_FORK_TURN_MIN_TICKS         200U
#define MED_CAR_FORK_TURN_TIMEOUT_MS       2500U

#define MED_CAR_RP2_WIGGLE_TICKS             300U
#define MED_CAR_RP2_WIGGLE_LEFT_PWM_LEFT    -1000
#define MED_CAR_RP2_WIGGLE_LEFT_PWM_RIGHT    1000
#define MED_CAR_RP2_WIGGLE_RIGHT_PWM_LEFT    1000
#define MED_CAR_RP2_WIGGLE_RIGHT_PWM_RIGHT  -1000
#define MED_CAR_RP2_WIGGLE_TIMEOUT_MS        5000U
#define MED_CAR_RP2_SCAN_TIMEOUT_MS          3000U
#define MED_CAR_RP2_SCAN_SETTLE_MS           200U
#define MED_CAR_RP2_TO_FORK_MAX_DISTANCE    200U
#define MED_CAR_RP2_MAX_COLLECTED            4U

typedef enum {
    MED_CAR_SENSOR_IO1 = 1,
    MED_CAR_SENSOR_IO2 = 2,
    MED_CAR_SENSOR_IO3 = 3,
    MED_CAR_SENSOR_IO4 = 4,
    MED_CAR_SENSOR_IO5 = 5,
    MED_CAR_SENSOR_IO6 = 6,
    MED_CAR_SENSOR_IO7 = 7,
    MED_CAR_SENSOR_IO8 = 8
} MedicineCarSensorId;

#endif
